name: Deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Push to gh-pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          build_dir: src
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
